import json
from rdkit import Chem
from rdkit.Chem import Draw


def draw_mibig_compounds(json_file):
    with open(json_file, "r") as f:
        data = json.load(f)
    compounds = data.get("compounds", [])

    # If a compound has no structure (SMILES), use * so that a molecule plot
    # can be generated by RDKit, in oder to show the molecule name as legend
    mols = [Chem.MolFromSmiles(c.get("structure", "*")) for c in compounds]
    names = [c.get("name", "") for c in compounds]

    svg = Draw.MolsToGridImage(
        mols,
        molsPerRow=len(mols),
        subImgSize=(300, 300),
        legends=names,
        useSVG=True
    )

    return svg
    