from rdkit import Chem
from rdkit.Chem import Draw


def draw_compounds(compounds):
    names, smiles = zip(*compounds) if compounds else ([], [])

    # If a compound has no SMILES, use * so that a molecule plot
    # is generated by RDKit and the molecule name is shown as a legend
    mols = [Chem.MolFromSmiles(s if s else "*") for s in smiles]

    svg = Draw.MolsToGridImage(
        mols, molsPerRow=len(mols), subImgSize=(300, 300), legends=names, useSVG=True
    )

    return svg
